// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: pb/proto/userservice.proto

package userservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	IsAuthorized(ctx context.Context, in *IsAuthorizedReq, opts ...grpc.CallOption) (*IsAuthorizedResp, error)
	LoginGame(ctx context.Context, opts ...grpc.CallOption) (UserService_LoginGameClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/userservice.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsAuthorized(ctx context.Context, in *IsAuthorizedReq, opts ...grpc.CallOption) (*IsAuthorizedResp, error) {
	out := new(IsAuthorizedResp)
	err := c.cc.Invoke(ctx, "/userservice.UserService/IsAuthorized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginGame(ctx context.Context, opts ...grpc.CallOption) (UserService_LoginGameClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/userservice.UserService/LoginGame", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceLoginGameClient{stream}
	return x, nil
}

type UserService_LoginGameClient interface {
	Send(*LoginGameReq) error
	Recv() (*LoginGameResp, error)
	grpc.ClientStream
}

type userServiceLoginGameClient struct {
	grpc.ClientStream
}

func (x *userServiceLoginGameClient) Send(m *LoginGameReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceLoginGameClient) Recv() (*LoginGameResp, error) {
	m := new(LoginGameResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	IsAuthorized(context.Context, *IsAuthorizedReq) (*IsAuthorizedResp, error)
	LoginGame(UserService_LoginGameServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServiceServer) IsAuthorized(context.Context, *IsAuthorizedReq) (*IsAuthorizedResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuthorized not implemented")
}
func (UnimplementedUserServiceServer) LoginGame(UserService_LoginGameServer) error {
	return status.Errorf(codes.Unimplemented, "method LoginGame not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userservice.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userservice.UserService/IsAuthorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsAuthorized(ctx, req.(*IsAuthorizedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).LoginGame(&userServiceLoginGameServer{stream})
}

type UserService_LoginGameServer interface {
	Send(*LoginGameResp) error
	Recv() (*LoginGameReq, error)
	grpc.ServerStream
}

type userServiceLoginGameServer struct {
	grpc.ServerStream
}

func (x *userServiceLoginGameServer) Send(m *LoginGameResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceLoginGameServer) Recv() (*LoginGameReq, error) {
	m := new(LoginGameReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userservice.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "IsAuthorized",
			Handler:    _UserService_IsAuthorized_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoginGame",
			Handler:       _UserService_LoginGame_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/proto/userservice.proto",
}
